In [3]:
import numpy as np


In [10]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [12]:
sample_list=[1,2,3]
           
sample_list

[1, 2, 3]

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [20]:
list_of_numbers=([1,2,3],[3,4,5],[7,8,9],[4,5,6])
np.array(list_of_numbers
        )

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9],
       [4, 5, 6]])

In [24]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [28]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
sample_array=np.arange(14)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [38]:
sample_array.reshape(14,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [39]:
sample_array.reshape(7,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [40]:
np.random.rand(4,5)

array([[0.63678455, 0.11216636, 0.5565848 , 0.137945  , 0.15133852],
       [0.70096499, 0.67059661, 0.5707256 , 0.82650129, 0.18129444],
       [0.65531132, 0.85920561, 0.16299935, 0.63199194, 0.581079  ],
       [0.35388922, 0.45192404, 0.674435  , 0.3024827 , 0.45386475]])

In [48]:
rand_array=np.random.randint(0,8,10)
rand_array

array([3, 6, 6, 5, 2, 5, 2, 6, 2, 7])

In [45]:
rand_array.max()

7

In [46]:
rand_array.min()

0

In [47]:
rand_array.argmax()

2

In [49]:
rand_array.argmin()


4